/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "USART_interface.h"

#include "BL.h"

int main(void)
{
	RCC_u8SetClksts(CLK_HSI, STATE_ON);
	RCC_SetSysClk(HSI);

	RCC_voidAPB1EnablePerapheralClock(APB1_USART2);
	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOA);
	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOC);
	RCC_voidAHB1EnablePerapheralClock(AHB1_CRC);
	RCC_voidAHB1EnablePerapheralClock_LowPower(AHB1L_FLIFT);
	USARTconfig_t USART_Cnfg;


	/*********************	GPIO Pins configurations ***********************/
	GPIO_PinConfig_T USARTPinRX =
	{
			.AltFunc = AF7,
			.Mode = ALTER_FUNC,
			.PinNum = PIN2,
			.Port = PORTA,
			.PullType = PUSH_PULL,
			.Speed = SPEED_LOW
	};

	GPIO_PinConfig_T USARTPinTX =
	{
			.AltFunc = AF7,
			.Mode = ALTER_FUNC,
			.PinNum = PIN3,
			.Port = PORTA,
			.PullType = PUSH_PULL,
			.Speed = SPEED_LOW
	};
	GPIO_PinConfig_T Button =
	{
			.Mode = INPUT,
			.PinNum = PIN13,
			.Port = PORTC,
			.PullType = NO_PULL
 	};

	/*********************	USART configuration	*************************/

	USART_Cnfg.DMAresevier = DMAR_DISABLE;
	USART_Cnfg.DMAtransmitter = DMAT_DISABLE;
	USART_Cnfg.ErrorTnterrupt = INHIBITED;
	USART_Cnfg.OverSampling = BY_16;
	USART_Cnfg.ParityControl = PARITY_CONTROL_DISABLE;
	USART_Cnfg.RXNEinterrupt = RXNE_INTERRUPT_DISABLE;
	USART_Cnfg.Receiver = RECEIVER_ENABLE;
	USART_Cnfg.StopBit_t = ONE_BIT;
	USART_Cnfg.TXEinterrupt = TXE_INTERRUPT_DISABLE;
	USART_Cnfg.TransmetCompleteInterrupt = TRANSMITTER_COMPLETE_INTERRUPT_DISABLE;
	USART_Cnfg.Transmitter = TRANSMITTER_ENABLE;
	USART_Cnfg.USARTindex = USART_2;
	USART_Cnfg.WordLength = DATA_8_BITS;
	USART_Cnfg.ParitySelection = PARITY_SELECTION_EVEN;


	/***********************	Button & LED Initialization ***********************/
	GPIO_u8PinInit(&Button);

	/***********************	MCAL Initialization ***********************/
	MUSART_u8SetConfiguration(&USART_Cnfg);
	GPIO_u8PinInit(&USARTPinRX);
	GPIO_u8PinInit(&USARTPinTX);



	/*********************************************************************/


	uint8_t Local_u8ButtonStatus;

	GPIO_u8ReadPinValue(Button.Port,Button.PinNum, &Local_u8ButtonStatus);

	/* Button is pressed*/
	if(Local_u8ButtonStatus == PIN_LOW)
	{
		/* jump to user application */
		BL_voidJumpToUserApp();

	}
	/* Button is not pressed*/
	else
	{
		/* receive packets from the host*/
		BL_voidReceivePckt();
	}
	while(1)
	{

	}
}
