#ifndef RCC_PRV_H_
#define RCC_PRV_H_

#define CLKYYPE_FLAG   	 	(ClkType + 1)
#define CLKYYPE_TIMEOUT 	50000U
#define ONE_BIT_MASKING 	1U
#define TWO_BITS_MASKING 	11U

typedef enum
{
	RCC_CR_HSION         =0,
	RCC_CR_HSIRDY        =1,
	RCC_CR_HSITRIM_0     =3,
	RCC_CR_HSITRIM_1     =4,
	RCC_CR_HSITRIM_2     =5,
	RCC_CR_HSITRIM_3     =6,
	RCC_CR_HSITRIM_4     =7,
	RCC_CR_HSICAL_0      =8,
	RCC_CR_HSICAL_1      =9,
	RCC_CR_HSICAL_2      =10,
	RCC_CR_HSICAL_3      =11,
	RCC_CR_HSICAL_4      =12,
	RCC_CR_HSICAL_5      =13,
	RCC_CR_HSICAL_6      =14,
	RCC_CR_HSICAL_7      =15,
	RCC_CR_HSEON  	     =16,
	RCC_CR_HSERDY        =17,
	RCC_CR_HSEBYP        =18,
	RCC_CR_CSSON  	     =19,
	RCC_CR_PLLON         =24,
	RCC_CR_PLLRDY	     =25,
    RCC_CR_PLLI2SON      =26,
	RCC_CR_PLLI2SRDY	 =27,
    RCC_CR_PLLSAION      =28,
	RCC_CR_PLLSAIRDY	 =29,
}RCC_CR_bits_t;
/*RCC_CFGR bits*/
typedef enum
{
	RCC_PLLLCFGR_PLLM_0	  =0,
	RCC_PLLLCFGR_PLLM_1	  =1,
	RCC_PLLLCFGR_PLLM_2	  =2,
	RCC_PLLLCFGR_PLLM_3	  =3,
	RCC_PLLLCFGR_PLLM_4	  =4,
	RCC_PLLLCFGR_PLLM_5	  =5,
	RCC_PLLLCFGR_PLLN_0	  =6,
	RCC_PLLLCFGR_PLLN_1	  =7,
	RCC_PLLLCFGR_PLLN_2   =8,
	RCC_PLLLCFGR_PLLN_3   =9,
	RCC_PLLLCFGR_PLLN_4   =10,
	RCC_PLLLCFGR_PLLN_5   =11,
	RCC_PLLLCFGR_PLLN_6   =12,
	RCC_PLLLCFGR_PLLN_7   =13,
	RCC_PLLLCFGR_PLLN_8   =14,
	RCC_PLLLCFGR_PLLP_0   =16,
	RCC_PLLLCFGR_PLLP_1   =17,
	RCC_PLLLCFGR_PLLSRC   =22,
	RCC_PLLLCFGR_PLLQ_0   =24,
	RCC_PLLLCFGR_PLLQ_1   =25,
	RCC_PLLLCFGR_PLLQ_2   =26,
	RCC_PLLLCFGR_PLLQ_3   =27,
	RCC_PLLLCFGR_USBPRE	  =22,
	RCC_PLLLCFGR_PLLR_0	  =28,
	RCC_PLLLCFGR_PLLR_1	  =29,
	RCC_PLLLCFGR_PLLR_2	  =30,
}RCC_PLLLCFGR_bits_t;
/*RCC_CFGR bits*/
typedef enum
{
	RCC_CFGR_SW_0	   =0,
	RCC_CFGR_SW_1	   =1,
	RCC_CFGR_SWS_0	   =2,
	RCC_CFGR_SWS_1	   =3,
	RCC_CFGR_HPRE_0	   =4,
	RCC_CFGR_HPRE_1	   =5,
	RCC_CFGR_HPRE_2	   =6,
	RCC_CFGR_HPRE_3	   =7,
	RCC_CFGR_PPRE1_0   =10,
	RCC_CFGR_PPRE1_1   =11,
	RCC_CFGR_PPRE1_2   =12,
	RCC_CFGR_PPRE2_0   =13,
	RCC_CFGR_PPRE2_1   =14,
	RCC_CFGR_PPRE2_2   =15,
	RCC_CFGR_RTCPRE_0  =16,
	RCC_CFGR_RTCPRE_1  =17,
    RCC_CFGR_RTCPRE_2  =18,
	RCC_CFGR_RTCPRE_3  =19,
    RCC_CFGR_RTCPRE_4  =20,
	RCC_CFGR_MCO1_0    =21,
	RCC_CFGR_MCO1_1    =22,
	RCC_CFGR_MCO1PRE_0 =24,
	RCC_CFGR_MCO1PRE_1 =25,
	RCC_CFGR_MCO1PRE_2 =26,
    RCC_CFGR_MCO2PRE_0 =27,
	RCC_CFGR_MCO2PRE_1 =28,
	RCC_CFGR_MCO2PRE_2 =29,
	RCC_CFGR_MCO2_0	   =30,
	RCC_CFGR_MCO2_1	   =31,
}RCC_CFGR_bits_t;

#endif