/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_interface.h"
#include "GPIO_interface.h"

#include "STM32F446xx.h"



int main(void)
{
	/*Relocate the vector table*/
	SCB->SCB_VTOR = 0X08008000 ;


	RCC_SetSysClk(HSI);

	RCC_voidAPB1EnablePerapheralClock(APB1_USART2);
	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOA);
	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOC);


	GPIO_PinConfig_T Button =
	{
			.Mode = INPUT,
			.PinNum = PIN13,
			.Port = PORTC,
			.PullType = NO_PULL
 	};

	GPIO_PinConfig_T LED =
	{
			.Mode = OUTPUT,
			.PinNum = PIN5,
			.Port = PORTA,
			.Speed = SPEED_HIGH
 	};

	GPIO_u8PinInit(&Button);
	GPIO_u8PinInit(&LED);

	uint8_t Local_u8ButtonStatus;
	while(1)
	{
		GPIO_u8ReadPinValue(Button.Port, Button.PinNum, &Local_u8ButtonStatus);
		if(Local_u8ButtonStatus == PIN_LOW)
		{
			GPIO_u8SetPinValue(LED.Port, LED.PinNum,PIN_HIGH);
		}
		else
		{
			GPIO_u8SetPinValue(LED.Port, LED.PinNum,PIN_LOW);

		}
	}
}
